version: 0.2

phases:
  install:
    commands:
      - echo "Install phase - setting up environment"
      - apt-get update -y
      - apt-get install -y maven

  pre_build:
    commands:
      - echo "Pre-build phase - preparing environment"
      - mvn clean

  build:
    commands:
      - echo "Build phase - compiling Java code"
      - mvn package -DskipTests

  post_build:
    commands:
      - echo "Post-build phase - preparing artifact"
      - ls target/
      - mv target/*.jar CRUD-Employee_Backend.jar

artifacts:
  files:
    - CRUD-Employee_Backend.jar
